# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sip', '0002_auto_20171122_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipstate',
            name='last_state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sipstate',
            name='username',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
